# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'commtools.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from Widget.CleanLabel import CleanLabel
from Widget.SaveLable import SaveLabel

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comSerialPort = QtWidgets.QComboBox(self.groupBox)
        self.comSerialPort.setMinimumSize(QtCore.QSize(100, 0))
        self.comSerialPort.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comSerialPort.setObjectName("comSerialPort")
        self.horizontalLayout.addWidget(self.comSerialPort)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comBaudRate = QtWidgets.QComboBox(self.groupBox)
        self.comBaudRate.setMinimumSize(QtCore.QSize(100, 0))
        self.comBaudRate.setObjectName("comBaudRate")
        self.horizontalLayout_2.addWidget(self.comBaudRate)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.comCheckBit = QtWidgets.QComboBox(self.groupBox)
        self.comCheckBit.setMinimumSize(QtCore.QSize(100, 0))
        self.comCheckBit.setObjectName("comCheckBit")
        self.horizontalLayout_3.addWidget(self.comCheckBit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.comDataBit = QtWidgets.QComboBox(self.groupBox)
        self.comDataBit.setMinimumSize(QtCore.QSize(100, 0))
        self.comDataBit.setObjectName("comDataBit")
        self.horizontalLayout_11.addWidget(self.comDataBit)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.comStopBit = QtWidgets.QComboBox(self.groupBox)
        self.comStopBit.setMinimumSize(QtCore.QSize(100, 0))
        self.comStopBit.setObjectName("comStopBit")
        self.horizontalLayout_4.addWidget(self.comStopBit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.btnOpenSerialPort = QtWidgets.QPushButton(self.groupBox)
        self.btnOpenSerialPort.setObjectName("btnOpenSerialPort")
        self.verticalLayout.addWidget(self.btnOpenSerialPort)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radbtnRcvASCII = QtWidgets.QRadioButton(self.groupBox_2)
        self.radbtnRcvASCII.setObjectName("radbtnRcvASCII")
        self.verticalLayout_2.addWidget(self.radbtnRcvASCII)
        self.radbtnRcvHex = QtWidgets.QRadioButton(self.groupBox_2)
        self.radbtnRcvHex.setObjectName("radbtnRcvHex")
        self.verticalLayout_2.addWidget(self.radbtnRcvHex)
        self.checkBoxRcvTime = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxRcvTime.setObjectName("checkBoxRcvTime")
        self.verticalLayout_2.addWidget(self.checkBoxRcvTime)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        # self.saveDatas = QtWidgets.QLabel(self.groupBox_2)
        self.saveDatas = SaveLabel(self.groupBox_2)
        self.saveDatas.setStyleSheet("font: 75 9pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.saveDatas.setObjectName("saveDatas")
        self.horizontalLayout_5.addWidget(self.saveDatas)
        # self.cleanDatas = QtWidgets.QLabel(self.groupBox_2)
        self.cleanDatas = CleanLabel(self.groupBox_2)
        self.cleanDatas.setStyleSheet("font: 75 9pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.cleanDatas.setObjectName("cleanDatas")
        self.horizontalLayout_5.addWidget(self.cleanDatas)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radbtnSenASCII = QtWidgets.QRadioButton(self.groupBox_3)
        self.radbtnSenASCII.setObjectName("radbtnSenASCII")
        self.verticalLayout_4.addWidget(self.radbtnSenASCII)
        self.radbtnSenHex = QtWidgets.QRadioButton(self.groupBox_3)
        self.radbtnSenHex.setObjectName("radbtnSenHex")
        self.verticalLayout_4.addWidget(self.radbtnSenHex)
        self.checkBoxSenAT = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxSenAT.setObjectName("checkBoxSenAT")
        self.verticalLayout_4.addWidget(self.checkBoxSenAT)
        self.checkBoxSenTime = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxSenTime.setObjectName("checkBoxSenTime")
        self.verticalLayout_4.addWidget(self.checkBoxSenTime)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 2, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radComAT = QtWidgets.QRadioButton(self.groupBox_4)
        self.radComAT.setObjectName("radComAT")
        self.horizontalLayout_8.addWidget(self.radComAT)
        self.radComATAMSLIST = QtWidgets.QRadioButton(self.groupBox_4)
        self.radComATAMSLIST.setObjectName("radComATAMSLIST")
        self.horizontalLayout_8.addWidget(self.radComATAMSLIST)
        self.radComATAMSSTATUS = QtWidgets.QRadioButton(self.groupBox_4)
        self.radComATAMSSTATUS.setObjectName("radComATAMSSTATUS")
        self.horizontalLayout_8.addWidget(self.radComATAMSSTATUS)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_8)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.textBrowserDebug = QtWidgets.QTextBrowser(self.groupBox_6)
        self.textBrowserDebug.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowserDebug.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textBrowserDebug.setObjectName("textBrowserDebug")
        self.verticalLayout_7.addWidget(self.textBrowserDebug)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        self.gridLayout.addLayout(self.verticalLayout_6, 1, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_14.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBoxDebug = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBoxDebug.setObjectName("checkBoxDebug")
        self.horizontalLayout_10.addWidget(self.checkBoxDebug)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.comChooseDevice = QtWidgets.QComboBox(self.groupBox_5)
        self.comChooseDevice.setObjectName("comChooseDevice")
        self.horizontalLayout_9.addWidget(self.comChooseDevice)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.textEditDeviceIp = QtWidgets.QLineEdit(self.groupBox_5)
        self.textEditDeviceIp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEditDeviceIp.setObjectName("textEditDeviceIp")
        self.textEditDeviceIp.setAlignment(QtCore.Qt.AlignBottom)
        self.horizontalLayout_12.addWidget(self.textEditDeviceIp)
        self.btnInputAdr = QtWidgets.QPushButton(self.groupBox_5)
        self.btnInputAdr.setObjectName("btnInputAdr")
        self.horizontalLayout_12.addWidget(self.btnInputAdr)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_12)
        self.gridLayout.addWidget(self.groupBox_5, 2, 0, 1, 2)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_16.addWidget(self.textEdit)
        self.btnSend = QtWidgets.QPushButton(self.centralwidget)
        self.btnSend.setObjectName("btnSend")
        self.horizontalLayout_16.addWidget(self.btnSend)
        self.gridLayout.addLayout(self.horizontalLayout_16, 3, 0, 1, 2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.Rx = QtWidgets.QLabel(self.centralwidget)
        self.Rx.setObjectName("Rx")
        self.horizontalLayout_7.addWidget(self.Rx)
        self.Tx = QtWidgets.QLabel(self.centralwidget)
        self.Tx.setObjectName("Tx")
        self.horizontalLayout_7.addWidget(self.Tx)
        self.btnReset = QtWidgets.QPushButton(self.centralwidget)
        self.btnReset.setObjectName("btnReset")
        self.horizontalLayout_7.addWidget(self.btnReset)
        self.horizontalLayout_7.setStretch(0, 2)
        self.horizontalLayout_7.setStretch(1, 1)
        self.horizontalLayout_7.setStretch(2, 1)
        self.gridLayout.addLayout(self.horizontalLayout_7, 4, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 17))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Modbus小助手1.0"))
        self.groupBox.setTitle(_translate("MainWindow", "串口设置"))
        self.label.setText(_translate("MainWindow", "串 口 号"))
        self.label_2.setText(_translate("MainWindow", "波 特 率"))
        self.label_3.setText(_translate("MainWindow", "校 验 位"))
        self.label_11.setText(_translate("MainWindow", "数 据 位"))
        self.label_12.setText(_translate("MainWindow", "停 止 位"))
        self.btnOpenSerialPort.setText(_translate("MainWindow", "打开"))
        self.groupBox_2.setTitle(_translate("MainWindow", "接收区设置"))
        self.radbtnRcvASCII.setText(_translate("MainWindow", "ASCII"))
        self.radbtnRcvHex.setText(_translate("MainWindow", "HEX"))
        self.checkBoxRcvTime.setText(_translate("MainWindow", "显示接收时间"))
        self.saveDatas.setText(_translate("MainWindow", " 保存数据 "))
        self.cleanDatas.setText(_translate("MainWindow", "清除显示"))
        self.groupBox_3.setTitle(_translate("MainWindow", "发送区设置"))
        self.radbtnSenASCII.setText(_translate("MainWindow", "ASCII"))
        self.radbtnSenHex.setText(_translate("MainWindow", "HEX"))
        self.checkBoxSenAT.setText(_translate("MainWindow", "AT命令"))
        self.checkBoxSenTime.setText(_translate("MainWindow", "显示发送时间"))
        self.groupBox_4.setTitle(_translate("MainWindow", "AT Command"))
        self.radComAT.setText(_translate("MainWindow", "AT"))
        self.radComATAMSLIST.setText(_translate("MainWindow", "ATAMSLIST"))
        self.radComATAMSSTATUS.setText(_translate("MainWindow", "ATAMSSTATUS"))
        self.groupBox_6.setTitle(_translate("MainWindow", "调试日志"))
        self.groupBox_5.setTitle(_translate("MainWindow", "现场调试"))
        self.checkBoxDebug.setText(_translate("MainWindow", "调试"))
        self.label_4.setText(_translate("MainWindow", "选择设备"))
        self.label_5.setText(_translate("MainWindow", "       "))
        self.label_13.setText(_translate("MainWindow", "输入地址"))
        self.btnInputAdr.setText(_translate("MainWindow", "确定"))
        self.btnSend.setText(_translate("MainWindow", "发送"))
        self.Rx.setText(_translate("MainWindow", "Rx:0 bytes"))
        self.Tx.setText(_translate("MainWindow", "Tx:0 bytes"))
        self.btnReset.setText(_translate("MainWindow", "复位计数"))

